
on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


name: Create tag

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          version: ${{ inputs.tag_name }}
          test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'